name: Deploy Production to gh-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      
      - name: Set production baseurl
        run: echo 'baseurl: "/IA340"' >> ./docs/_config.yml
