name: Deploy Production to gh-pages

on:
  push:
    branches:
      - main

concurrency:
  group: ia340-gh-pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set production baseurl
        run: |
          echo 'baseurl: "/IA340"' >> ./docs/_config.yml

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs/
          destination: ./_site

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4
        with:
          folder: ./_site
          branch: gh-pages
          clean-exclude: pr-preview
