name: PR Preview
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      
      - name: Test if
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: echo "same repo"
