name: PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency:
  group: ia340-gh-pages
  cancel-in-progress: false

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set PR baseurl
        if: github.event.action != 'closed'
        run: |
          echo 'baseurl: "/IA340/pr-preview/pr-${{ github.event.number }}"' >> ./docs/_config.yml

      - name: Build with Jekyll
        if: github.event.action != 'closed'
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs/
          destination: ./_site

      - name: Deploy PR Preview
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: rossjrw/pr-preview-action@df22037db54ab6ee34d3c1e2b8810ac040a530c6 # v1.6.0
        with:
          source-dir: ./_site
          preview-branch: gh-pages
          umbrella-dir: pr-preview
