name: PR Preview
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
